name: FortiClient VPN Test

on:
  workflow_dispatch:

jobs:
  vpn-test:
    runs-on: ubuntu-latest

    steps:
      - name: Install FortiClient
        run: |
          wget https://links.fortinet.com/forticlient/debian/vpnagent-linux.deb
          sudo apt-get update
          sudo apt-get install -y ./vpnagent-linux.deb

      - name: Connect to FortiClient VPN
        run: |
          echo "Starting FortiClient VPN..."
          fortivpn --server ${{ secrets.VPN_HOST }} \
                   --vpnuser ${{ secrets.VPN_USER }} \
                   --password ${{ secrets.VPN_PWD }} \
                   || echo "VPN connection failed." && exit 1

      - name: Test VPN Connection
        run: |
          echo "Testing VPN connection..."
          ifconfig || sudo apt-get update && sudo apt-get install -y net-tools
          ifconfig | grep tun0 || (echo "VPN connection failed: tun0 not found." && exit 1)
          echo "VPN connected successfully."
 
