name: FortiClient VPN Connection and SSH Test

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  vpn_connect:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install openfortivpn
        run: |
          sudo apt-get update
          sudo apt-get install -y openfortivpn

      - name: Configure VPN connection
        env:
          VPN_HOST: 85.98.92.196
          VPN_USERNAME: metropols4in
          VPN_PASSWORD: M3tr0pols4in..
          VPN_PORT: 19443
        run: |
          echo -e "[vpn]\nhost = metropols4in.vpn.server\nport = 19443\nusername = metropols4in\npassword = M3tr0pols4in.." > vpn.conf
          sudo openfortivpn -c vpn.conf -v --insecure

      - name: Check VPN Connectivity
        run: |
          ping -c 10 192.168.25.9

      - name: Execute remote SSH commands
        uses: appleboy/ssh-action@master
        with:
          host: 192.168.25.9
          username: depo
          password: poNti2024!!
          port: 22
          timeout: 120s
          command_timeout: 15m
          script: |
            echo "VPN bağlantısı başarılı. SSH üzerinden komut çalıştırılıyor."
            cd /data/projects/MetropolUnFlowIntegration
            git pull https://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@github.com/mehmetmk35/NODE-RED_MetroFlowI_ntegration.git
