name: FortiClient VPN Connection

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  vpn_connect:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Test Initial Connection
        run: ifconfig

      - name: Forticlient VPN
        uses: horellana/openconnect@v1.0.1
        with:
          VPN_USER: ${{ secrets.VPN_USER }}
          VPN_PWD: ${{ secrets.VPN_PWD }}
          VPN_HOST: ${{ secrets.VPN_HOST }}
          VPN_PORT: 19443
     

      - name: Test VPN Connection
        run: |
          ifconfig | grep tun0 || exit 1
          ping -c 4 ${{ secrets.INTERNAL_SERVER_IP }}

      - name: Test SSH Connection
        run: |
          ssh -o StrictHostKeyChecking=no -p ${{ secrets.PROD_SSH_PORT }} ${{ secrets.PROD_SSH_USERNAME }}@${{ secrets.PROD_SSH_HOST }} echo "SSH connection successful"

      - name: Execute Remote SSH Commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_SSH_HOST }}
          username: ${{ secrets.PROD_SSH_USERNAME }}
          password: ${{ secrets.PROD_SSH_PASSWORD }}
          port: ${{ secrets.PROD_SSH_PORT }}
          script: |
            docker exec -it 2d5c3835ffb7 /bin/bash
            cd /data/projects/MetropolUnFlowIntegration
            git pull https://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@github.com/mehmetmk35/NODE-RED_MetroFlowI_ntegration.git
