name: FortiClient VPN Connection

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  vpn_connect:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Install curl and required dependencies
      - name: Install required dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl wget lsb-release apt-transport-https

      # Step 2: Download the FortiClient .deb package from Fortinet
      - name: Download FortiClient
        run: |
          curl -LO https://fortinet.com/downloads/forticlient_7.2.0_amd64.deb  # Ensure this URL is correct
          
      # Step 3: Install the downloaded FortiClient package using dpkg
      - name: Install FortiClient
        run: |
          sudo dpkg -i forticlient_7.2.0_amd64.deb
          sudo apt-get install -f -y  # Install missing dependencies if any

      # Step 4: Connect to FortiClient VPN
      - name: Connect to FortiClient VPN
        run: |
          echo "Starting FortiClient VPN..."
          echo ${{ secrets.VPN_PWD }} | sudo forticlient connect -s ${{ secrets.VPN_HOST }}:${{ secrets.VPN_PORT }} --vpnuser ${{ secrets.VPN_USER }} --passwd stdin

      # Step 5: Execute remote SSH commands
      - name: Execute remote SSH commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_SSH_HOST }}
          username: ${{ secrets.PROD_SSH_USERNAME }}
          password: ${{ secrets.PROD_SSH_PASSWORD }}
          port: ${{ secrets.PROD_SSH_PORT }}
          script: |
            docker exec -it 2d5c3835ffb7 /bin/bash
            cd /data/projects/MetropolUnFlowIntegration
            git pull https://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@github.com/mehmetmk35/NODE-RED_MetroFlowI_ntegration.git
