name: FortiClient VPN Connection

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  vpn_connect:
    runs-on: ubuntu-latest

    steps:
      # Kodu al
      - name: Checkout Code
        uses: actions/checkout@v4

      # FortiClient VPN bağlantısı
      - name: Forticlient VPN
        uses: horellana/openconnect@v1.0.1
        with:
          VPN_USER: ${{ secrets.VPN_USER }}
          VPN_PWD: ${{ secrets.VPN_PWD }}
          VPN_HOST: ${{ secrets.VPN_HOST }}
          VPN_PORT: 19443
          VPN_SERVER_CERT: ${{ secrets.VPN_SERVER_CERT }}      

      # VPN bağlantısından sonra SSH ile komut çalıştırma
      - name: Execute remote SSH commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_SSH_HOST }}
          username: ${{ secrets.PROD_SSH_USERNAME }}
          password: ${{ secrets.PROD_SSH_PASSWORD }}
          port: ${{ secrets.PROD_SSH_PORT }}
          script: |    
           docker exec -it 2d5c3835ffb7 /bin/bash
           cd /data/projects/MetropolUnFlowIntegration
           git pull https://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@github.com/mehmetmk35/NODE-RED_MetroFlowI_ntegration.git

      # Ağ Bağlantısını Test Etme (Alternatif yöntem)
      - name: Test Network Connectivity with nc
        run: nc -zv ${{ secrets.PROD_SSH_HOST }} ${{ secrets.PROD_SSH_PORT }}
