name: FortiClient VPN Connection

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  vpn_connect:
    runs-on: ubuntu-latest

    steps:
      - name: Add FortiClient Repository
        run: |
          echo "deb [arch=amd64] https://repo.fortinet.com/forticlient/debian/ stable multiverse" | sudo tee -a /etc/apt/sources.list.d/forticlient.list
          sudo apt-get update || { echo "Failed to update repositories. Exiting..."; exit 1; }

      - name: Install FortiClient
        run: |
          sudo apt-get install -y forticlient || { echo "FortiClient installation failed. Exiting..."; exit 1; }

      - name: Connect to FortiClient VPN
        run: |
          echo "Starting FortiClient VPN..."
          echo ${{ secrets.VPN_PWD }} | forticlient connect -s ${{ secrets.VPN_HOST }}:${{ secrets.VPN_PORT }} --vpnuser ${{ secrets.VPN_USER }} --passwd stdin

      - name: Execute remote SSH commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_SSH_HOST }}
          username: ${{ secrets.PROD_SSH_USERNAME }}
          password: ${{ secrets.PROD_SSH_PASSWORD }}
          port: ${{ secrets.PROD_SSH_PORT }}
          script: |
            docker exec -it 2d5c3835ffb7 /bin/bash
            cd /data/projects/MetropolUnFlowIntegration
            git pull https://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@github.com/mehmetmk35/NODE-RED_MetroFlowI_ntegration.git
