name: FortiClient VPN Connection

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  vpn_connect:
    runs-on: ubuntu-latest

    steps:
      - name: Update and Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl wget

      - name: Download FortiClient .deb Package
        run: |
          # Replace with the correct download URL for the FortiClient .deb package
          curl -LO https://fortinet.com/downloads/forticlient_7.2.0_amd64.deb

      - name: Verify the downloaded file
        run: |
          # Check if the file is a valid Debian package
          file forticlient_7.2.0_amd64.deb
          # Verify the package integrity (optional)
          dpkg-deb --info forticlient_7.2.0_amd64.deb

      - name: Install FortiClient
        run: |
          # Install the FortiClient package using apt to handle dependencies
          sudo apt-get install -y ./forticlient_7.2.0_amd64.deb

      - name: Connect to FortiClient VPN
        run: |
          echo "Starting FortiClient VPN..."
          echo ${{ secrets.VPN_PWD }} | forticlient connect -s ${{ secrets.VPN_HOST }}:${{ secrets.VPN_PORT }} --vpnuser ${{ secrets.VPN_USER }} --passwd stdin

      - name: Execute remote SSH commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_SSH_HOST }}
          username: ${{ secrets.PROD_SSH_USERNAME }}
          password: ${{ secrets.PROD_SSH_PASSWORD }}
          port: ${{ secrets.PROD_SSH_PORT }}
          script: |
            docker exec -it 2d5c3835ffb7 /bin/bash
            cd /data/projects/MetropolUnFlowIntegration
            git pull https://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@github.com/mehmetmk35/NODE-RED_MetroFlowI_ntegration.git
