name: FortiClient VPN Connection

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  vpn_connect:
    runs-on: ubuntu-latest

    steps:
      - name: Install OpenFortiVPN
        run: |
          sudo apt-get update
          sudo apt-get install -y openfortivpn

      - name: Configure VPN
        env:
          VPN_USER: metropols4in
          VPN_PWD: M3tr0pols4in..
          VPN_HOST: 85.98.92.196
        run: |
          echo "[openfortivpn]
          host = 85.98.92.196
          port = 19443
          username = metropols4in
          password = M3tr0pols4in.." > vpn-config.conf

      - name: Connect to VPN
        run: sudo openfortivpn -c vpn-config.conf --trusted-cert "" &

      - name: Wait for VPN Connection
        run: sleep 20

      - name: Debug VPN Connection
        run: sudo cat /var/log/syslog | grep openfortivpn

      - name: Check Network Interfaces
        run: ip addr

      - name: Check VPN Connectivity
        run: |
          ping -c 10 192.168.25.9

      - name: Execute remote SSH commands
        uses: appleboy/ssh-action@master
        with:
          host: 192.168.25.9
          username: depo
          password: poNti2024!!
          port: 22
          timeout: 120s
          command_timeout: 15m
          script: |
            cd /data/projects/MetropolUnFlowIntegration
            git pull https://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@github.com/mehmetmk35/NODE-RED_MetroFlowI_ntegration.git
