name: FortiClient VPN Connection

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  vpn_connect:
    runs-on: ubuntu-latest

    steps:
     - name: Update System and Install FortiClient
       run: sudo apt-get update
          sudo apt-get install -y curl wget
          curl -LO https://forticlient.com/downloads/forticlient_7.2.0_amd64.deb
          sudo apt-get install -y ./forticlient_7.2.0_amd64.deb

     - name: Connect to VPN with FortiClient
       run: |
          echo "${{ secrets.VPN_PASSWORD }}" | forticlient connect \
            --server ${{ secrets.VPN_SERVER }} \
            --user ${{ secrets.VPN_USER }} \
            --passwd stdin       

     - name: Execute Remote SSH Commands
       uses: appleboy/ssh-action@master
       with:
          host: ${{ secrets.PROD_SSH_HOST }}
          username: ${{ secrets.PROD_SSH_USERNAME }}
          password: ${{ secrets.PROD_SSH_PASSWORD }}
          port: ${{ secrets.PROD_SSH_PORT }}
          script: |
            docker exec -it 2d5c3835ffb7 /bin/bash
            cd /data/projects/MetropolUnFlowIntegration
            git pull https://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@github.com/mehmetmk35/NODE-RED_MetroFlowI_ntegration.git
