name: FortiClient VPN Connection

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  vpn_connect:
    runs-on: ubuntu-latest

    steps:
      - name: Update and Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libnss3-tools ppp libappindicator1 expect ca-certificates libsecret-1-0

      - name: Download FortiClient .deb Package
        run: |
          wget https://filestore.fortinet.com/forticlient/forticlient_vpn_7.4.0.1636_amd64.deb -O forticlient.deb
          sudo dpkg -i forticlient.deb

      - name: Create VPN Profile
        run: |
          echo '#!/usr/bin/expect -f' > create_vpn_profile.exp
          echo 'spawn /opt/forticlient/fortivpn edit myvpn' >> create_vpn_profile.exp
          echo 'expect -re "Type"' >> create_vpn_profile.exp
          echo 'send -- "1\r"' >> create_vpn_profile.exp
          echo 'expect -re "Remote Gateway:"' >> create_vpn_profile.exp
          echo 'send -- "85.98.92.196\r"' >> create_vpn_profile.exp
          echo 'expect -re "Port"' >> create_vpn_profile.exp
          echo 'send -- "19443\r"' >> create_vpn_profile.exp
          echo 'expect -re "Authentication"' >> create_vpn_profile.exp
          echo 'send -- "3\r"' >> create_vpn_profile.exp
          echo 'expect -re "Certificate"' >> create_vpn_profile.exp
          echo 'send -- "3\r"' >> create_vpn_profile.exp
          echo 'expect eof' >> create_vpn_profile.exp
          chmod +x create_vpn_profile.exp
          ./create_vpn_profile.exp
          cat create_vpn_profile.exp

      - name: Connect to FortiClient VPN
        run: |
          echo '#!/usr/bin/expect -f' > vpnconnect.exp
          echo 'spawn /opt/forticlient/fortivpn connect myvpn --user=metropols4in --password -s' >> vpnconnect.exp
          echo 'expect -exact "Password:"' >> vpnconnect.exp
          echo 'send -- "M3tr0pols4in..\r"' >> vpnconnect.exp
          echo 'expect -re "Confirm "' >> vpnconnect.exp
          echo 'send -- "y\r"' >> vpnconnect.exp
          echo 'expect eof' >> vpnconnect.exp
          chmod +x vpnconnect.exp
          ./vpnconnect.exp
          cat vpnconnect.exp

      - name: VPN Status
        run: |
          /opt/forticlient/fortivpn status

      - name: Check VPN Connectivity
        run: |
          ping -c 10 192.168.25.9

      - name: Execute remote SSH commands
        uses: appleboy/ssh-action@master
        with:
          host: 192.168.25.9
          username: depo
          password: poNti2024!!
          port: 22
          timeout: 120s
          command_timeout: 15m
          script: |
            docker exec -it 2d5c3835ffb7 /bin/bash
            cd /data/projects/MetropolUnFlowIntegration
            git pull https://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@github.com/mehmetmk35/NODE-RED_MetroFlowI_ntegration.git
