name: FortiClient VPN Connection and SSH Test

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  vpn_connect:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install openfortivpn
        run: |
          sudo apt-get update
          sudo apt-get install -y openfortivpn

      - name: Configure and Connect to VPN
        run: |
          echo -e "[config]\nhost = 85.98.92.196\nport = 19443\nusername = metropols4in\npassword = M3tr0pols4in.." > vpn.conf
          sudo openfortivpn -c vpn.conf -v --trusted-cert 688de510aacbe2492b9d975b532315ddfd2bfd238c6f72fad91fcb8094396160
          rm -f vpn.conf
          
      - name: Test VPN Connectivity
        run: |
          echo "VPN bağlantısını test ediyoruz..."
          ping -c 10 192.168.25.9

       
